[system]
financial_institution_detector = '''
<metadata>
version = "0.1.0"
author = "Bruno Bertholdi"
last_updated = "2025-02-11"
</metadata>

<persona>
Você é um detector preciso de instituições financeiras em textos.
</persona>

<goal>
Analisar o <raw-text> e identificar a instituição financeira mencionada ou relacionada. Responder apenas com o nome da instituição. Se não identificada, responder "Não identificado".
</goal>

<instructions>
- Identificar bancos, cooperativas de crédito, financeiras e outras instituições do setor.
- Considerar menções diretas, descrições de logotipos e informações contextuais.
- Responder de forma concisa, apenas com o nome da instituição.
- Não incluir explicações ou informações adicionais na resposta.
</instructions>
'''


bradesco_data_extractor = '''
<metadata>
version = "0.1.0"
author = "Bruno Bertholdi"
creation_date = "2025-02-11"
</metadata>

<persona>
Você é um extrator de dados preciso e confiável, especializado em documentos do Bradesco.
</persona>

<goal>
Extrair dados estruturados de documentos do Bradesco, mantendo a precisão e o formato exato dos dados.
</goal>

<instructions>
Analise o texto em <raw-text> e extraia os dados conforme as regras abaixo:

1. Formato: Retorne os dados em formato JSON, seguindo exatamente a estrutura fornecida.
2. Campos vazios: Para campos não encontrados no documento, use uma string vazia ("").
3. Checkboxes: Em <raw-text>, checkboxes preenchidas são identificadas com "[Y]", "Y]" ou variações. Para campos de checkbox:
   - Se encontrar marcação, retorne "Sim"
   - Se encontrar checkbox não marcada, retorne "Não"
   - Se não encontrar checkbox mas houver opções Sim/Não, retorne "N/A"
4. E-mails: Corrija e-mails que:
   - Contenham espaços (substitua por "_")
   - Usem letras no lugar de "@" (substitua pela @)
5. Valores monetários: Use formato "R$ X.XXX,XX"
6. CPF/CNPJ: Mantenha pontuação (ex: 123.456.789-00)

Estrutura de dados para extração:
{input}
</instructions>
'''


[user]
financial_institution_detector = '''
<user-instructions>
Identifique a instituição financeira mencionada no texto abaixo:

<raw-text>
{input}
</raw-text>
</user-instructions>
'''

bradesco_data_extractor = '''
<user-instructions>
Identifique e extraia os dados do seguinte texto:

<raw-text>
{input}
</raw-text>

Retorne os dados exatamente neste formato JSON, preenchendo os valores conforme encontrados no texto:

{{
    "dados_do_1o_comprador": {{
        "nome_completo": "",
        "cpf_mf": "",
        "profissao": "",
        "e_mail": "",
        "estado_civil": "",
        "campo_obrigatorio_para_quem_nao_e_casado_vive_em_uniao_estavel": "",
        "e_funcionario_da_organizacao_bradesco_ou_parente_de_primeiro_grau_pai_ou_filho": "",
        "se_sim_informe_codigo_funcional": ""
    }},
    "dados_do_2o_comprador": {{
        "nome_completo": "",
        "cpf_mf": "",
        "profissao": "",
        "e_mail": "",
        "estado_civil": "",
        "campo_obrigatorio_para_quem_nao_e_casado_vive_em_uniao_estavel": "",
        "e_funcionario_da_organizacao_bradesco_ou_parente_de_primeiro_grau_pai_ou_filho": "",
        "se_sim_informe_codigo_funcional": ""
    }},
    "dados_do_3o_comprador": {{
        "nome_completo": "",
        "cpf_mf": "",
        "profissao": "",
        "e_mail": "",
        "estado_civil": "",
        "campo_obrigatorio_para_quem_nao_e_casado_vive_em_uniao_estavel": "",
        "e_funcionario_da_organizacao_bradesco_ou_parente_de_primeiro_grau_pai_ou_filho": "",
        "se_sim_informe_codigo_funcional": ""
    }},
    "dados_do_4o_comprador": {{
        "nome_completo": "",
        "cpf_mf": "",
        "profissao": "",
        "e_mail": "",
        "estado_civil": "",
        "campo_obrigatorio_para_quem_nao_e_casado_vive_em_uniao_estavel": "",
        "e_funcionario_da_organizacao_bradesco_ou_parente_de_primeiro_grau_pai_ou_filho": "",
        "se_sim_informe_codigo_funcional": ""
    }},
    "dados_bancarios_pagamento_das_prestacoes": {{
        "autorizo_o_debito_pagamento_do_valor_das_prestacoes_por_meio_de": "",
        "para_opcao_de_pagamento_das_prestacoes_por_meio_debito_em_conta_corrente_informar": "",
        "conta_de_titularidade_do_comprador_que_autorizou_o_debito": "",
        "nome": "",
        "agencia_debito_parcela": "",
        "conta_debito_parcela": "",
        "digito_conta": "",
        "autorizo_utilizar_o_limite_de_credito_incluindo_o_cheque_especial_se_contratados_quando_nao_houver_saldo_em_conta": "",
        "autorizo_o_debito_do_valor_da_s_prestacao_s_vencida_s_inclusive_de_valor_es_parcial_is_os_encargos_serao_incorporados_nas_prestacoes_seguintes_conforme_detalhado_em_contrato": ""
    }},
    "dados_do_s_1o_vendedor_es_pessoa_fisica_pessoa_juridica": {{
        "nome_completo_razao_social": "",
        "cpf_cnpj_mf": "",
        "profissao": "",
        "e_mail": "",
        "estado_civil": "",
        "campo_obrigatorio_para_quem_nao_e_casado_vive_em_uniao_estavel": "",
        "forma_de_recebimento": "",
        "banco": "",
        "agencia": "",
        "digito": "",
        "conta": "",
        "digito": ""
    }},
    "dados_do_s_2o_vendedor_es_pessoa_fisica_pessoa_juridica": {{
        "nome_completo_razao_social": "",
        "cpf_cnpj_mf": "",
        "profissao": "",
        "e_mail": "",
        "estado_civil": "",
        "campo_obrigatorio_para_quem_nao_e_casado_vive_em_uniao_estavel": "",
        "forma_de_recebimento": "",
        "banco": "",
        "agencia": "",
        "digito": "",
        "conta": "",
        "digito": ""
    }},
    "dados_do_imovel_a_ser_financiado": {{
        "endereco": "",
        "numero": "",
        "complemento": "",
        "quantidade_de_vagas": "",
        "n_de_vagas": "",
        "quantidade_deposito_box": "",
        "n_deposito_box": ""
    }},
    "condicoes_da_operacao_todos_os_itens_deste_bloco_sao_de_preenchimento_obrigatorio": {{
        "valor_da_compra_venda": "",
        "valor_de_financiamento": "",
        "ira_utilizar_o_fgts": "",
        "prazo_de_amortizacao": "",
        "dia_base_para_pagamento_das_prestacoes_de_01_a_28": "",
        "sistema_de_amortizacao": "",
        "deseja_incluir_despesas_cartorarias_no_financiamento": ""
    }},
    "aceite_registro_eletronico_assinatura_digital": "",
    "declaracoes_do_s_comprador_es": {{
        "o_s_comprador_es_concordam_com_a_dispensa": "",
        "declaracao_de_inexistencia_de_debitos_condominiais": "",
        "certidao_negativa_de_impostos_e_taxas_municipais": "",
        "declaracao_de_regularidade_de_foro_para_imoveis_foreiros": ""
    }}
}}

Observações importantes:
1. Para campos não encontrados no documento, use uma string vazia ("").
2. Para campos de checkbox:
   - Se encontrar marcação ([Y], Y] ou variações), retorne "Sim"
   - Se encontrar checkbox não marcada, retorne "Não"
   - Se não encontrar checkbox mas houver opções Sim/Não, retorne "N/A"
3. Para e-mails:
   - Substitua espaços por "_"
   - Substitua letras usadas no lugar de "@" pelo próprio "@"
4. Para valores monetários, use o formato "R$ X.XXX,XX"
5. Para CPF/CNPJ, mantenha a pontuação (ex: 123.456.789-00)
</user-instructions>
'''
