[system]
financial_institution_detector = '''
<metadata>
version = "0.1.0"
author = "Bruno Bertholdi"
last_updated = "2025-02-11"
</metadata>

<persona>
Você é um detector preciso de instituições financeiras em textos.
</persona>

<goal>
Analisar o <raw-text> e identificar a instituição financeira mencionada ou relacionada. Responder apenas com o nome da instituição. Se não identificada, responder "Não identificado".
</goal>

<instructions>
- Identificar bancos, cooperativas de crédito, financeiras e outras instituições do setor.
- Considerar menções diretas, descrições de logotipos e informações contextuais.
- Responder de forma concisa, apenas com o nome da instituição.
- Não incluir explicações ou informações adicionais na resposta.
</instructions>
'''


bradesco_data_extractor = '''
<metadata>
version = "0.1.0"
author = "Bruno Bertholdi"
creation_date = "2025-02-11"
</metadata>

<persona>
Sou um assistente de extração de dados não estruturados e que trabalha com documentos escritos em português.
Sou capaz de compreender, organizar e extrair dados de forma estruturada e organizada.
Minha função é somente organizar e extrair dados.
Eu não possuo qualquer interface com o usuário, apenas com o documento em si.
</persona>

<goal>
1. Ler o documento recebido;
2. Extrair dados do documento;
3. Organizar os dados em uma estrutura determinada pelo usuário;
4. Retornar os dados organizados para o usuário;
</goal>

<instructions>
1. Caso a query do usuário solicite algo diferente do indicado em <goal>, devo responder com uma mensagem que indique minha incapacidade de atender a essa query;
2. Eu não devo citar a tag <metadata>;
3. Eu não devo citar a tag <persona>;
4. Eu não devo citar a tag <goal>;
5. Eu não devo citar a tag <instructions>.
</instructions>
'''

[user]
financial_institution_detector = '''
<raw-text>
{input}
</raw-text>

<user-instructions>
Identifique e retorne apenas o nome da instituição financeira mencionada em <raw-text> e me retorne em uma string.
</user-instructions>
'''


bradesco_data_extractor = '''
<raw-text>
{input}
</raw-text>

<user-instructions>
Identifique e extraia os seguintes dados de <raw-text>
- Dados do 1º Comprador:
    - Nome Completo:
    - CPF/MF: # Exemplo de CPF: 928.064.123-00
    - Profissão:
    - E-mail: # Emails podem vir com um espaço em branco e com alguma letra no lugar de "@", por exemplo: "nagyla pollyanaQhotmail.com". Corrija estes casos, adicionando um "_" no lugar do espaço e "@" entre o nome e o domínio.
    - Estado Civil: # Solteiro, Casado, Divorciado, Viuvo
    - Campo obrigatório para quem não é casado. Vive em união estável? # Este campo é identificado por um checkbox. Em <raw-text>, checkboxes preenchidas são identificadas com "[Y]", "Y]" ou variações dessa estrutura. Caso se depare com linhas que contenham "Sim" e "Não", mas que não venham acompanhadas do identificador de preenchimento, interprete que o usuário não respondeu a essa pergunta e preencha com "N/A".
    - É funcionário da Organização Bradesco ou parente de primeiro grau (pai ou filho)? # Este campo é identificado como um checkbox. Em <raw-text>, checkboxes preenchidas são identificadas com "[Y]", "Y]" ou variações dessa estrutura. Caso se depare com linhas que contenham "Sim" e "Não", mas que não venham acompanhadas do identificador de preenchimento, interprete que o usuário não respondeu a essa pergunta e preencha com "N/A".
    - Se sim, informe código funcional: # Só será preenchido caso o usuário responda "Sim" no campo "É funcionário da Organização Bradesco ou parente de primeiro grau (pai ou filho)?"
- Dados do 2º Comprador:
    - Nome Completo:
    - CPF/MF: # Exemplo de CPF: 928.064.123-00
    - Profissão:
    - E-mail: # Emails podem vir com um espaço em branco e com alguma letra no lugar de "@", por exemplo: "nagyla pollyanaQhotmail.com". Corrija estes casos, adicionando um "_" no lugar do espaço e "@" entre o nome e o domínio.
    - Estado Civil: # Solteiro, Casado, Divorciado, Viuvo
    - Campo obrigatório para quem não é casado. Vive em união estável? # Este campo é identificado por um checkbox. Em <raw-text>, checkboxes preenchidas são identificadas com "[Y]", "Y]" ou variações dessa estrutura. Caso se depare com linhas que contenham "Sim" e "Não", mas que não venham acompanhadas do identificador de preenchimento, interprete que o usuário não respondeu a essa pergunta e preencha com "N/A".
    - É funcionário da Organização Bradesco ou parente de primeiro grau (pai ou filho)? # Este campo é identificado como um checkbox. Em <raw-text>, checkboxes preenchidas são identificadas com "[Y]", "Y]" ou variações dessa estrutura. Caso se depare com linhas que contenham "Sim" e "Não", mas que não venham acompanhadas do identificador de preenchimento, interprete que o usuário não respondeu a essa pergunta e preencha com "N/A".
    - Se sim, informe código funcional: # Só será preenchido caso o usuário responda "Sim" no campo "É funcionário da Organização Bradesco ou parente de primeiro grau (pai ou filho)?"
- Dados do 3º Comprador:
    - Nome Completo:
    - CPF/MF: # Exemplo de CPF: 928.064.123-00
    - Profissão:
    - E-mail: # Emails podem vir com um espaço em branco e com alguma letra no lugar de "@", por exemplo: "nagyla pollyanaQhotmail.com". Corrija estes casos, adicionando um "_" no lugar do espaço e "@" entre o nome e o domínio.
    - Estado Civil: # Solteiro, Casado, Divorciado, Viuvo
    - Campo obrigatório para quem não é casado. Vive em união estável? # Este campo é identificado por um checkbox. Em <raw-text>, checkboxes preenchidas são identificadas com "[Y]", "Y]" ou variações dessa estrutura. Caso se depare com linhas que contenham "Sim" e "Não", mas que não venham acompanhadas do identificador de preenchimento, interprete que o usuário não respondeu a essa pergunta e preencha com "N/A".
    - É funcionário da Organização Bradesco ou parente de primeiro grau (pai ou filho)? # Este campo é identificado como um checkbox. Em <raw-text>, checkboxes preenchidas são identificadas com "[Y]", "Y]" ou variações dessa estrutura. Caso se depare com linhas que contenham "Sim" e "Não", mas que não venham acompanhadas do identificador de preenchimento, interprete que o usuário não respondeu a essa pergunta e preencha com "N/A".
    - Se sim, informe código funcional: # Só será preenchido caso o usuário responda "Sim" no campo "É funcionário da Organização Bradesco ou parente de primeiro grau (pai ou filho)?"
- Dados do 4º Comprador:
    - Nome Completo:
    - CPF/MF: # Exemplo de CPF: 928.064.123-00
    - Profissão:
    - E-mail: # Emails podem vir com um espaço em branco e com alguma letra no lugar de "@", por exemplo: "nagyla pollyanaQhotmail.com". Corrija estes casos, adicionando um "_" no lugar do espaço e "@" entre o nome e o domínio.
    - Estado Civil: # Solteiro, Casado, Divorciado, Viuvo
    - Campo obrigatório para quem não é casado. Vive em união estável? # Este campo é identificado por um checkbox. Em <raw-text>, checkboxes preenchidas são identificadas com "[Y]", "Y]" ou variações dessa estrutura. Caso se depare com linhas que contenham "Sim" e "Não", mas que não venham acompanhadas do identificador de preenchimento, interprete que o usuário não respondeu a essa pergunta e preencha com "N/A".
    - É funcionário da Organização Bradesco ou parente de primeiro grau (pai ou filho)? # Este campo é identificado como um checkbox. Em <raw-text>, checkboxes preenchidas são identificadas com "[Y]", "Y]" ou variações dessa estrutura. Caso se depare com linhas que contenham "Sim" e "Não", mas que não venham acompanhadas do identificador de preenchimento, interprete que o usuário não respondeu a essa pergunta e preencha com "N/A".
    - Se sim, informe código funcional: # Só será preenchido caso o usuário responda "Sim" no campo "É funcionário da Organização Bradesco ou parente de primeiro grau (pai ou filho)?"
- Dados Bancários - Pagamento das Prestações:
    - Autorizo o débito / pagamento do valor das parcelas por meio de: # Este campo é identificado por um checkbox.
    - Para opção de pagamento das parcelas por meio débito em conta corrente, informar:
    - Conta de titularidade do Comprador que autorizou o débito:
        - Nome:
        - Agência Débito Parcela:
        - Conta Débito Parcela:
        - Dígito Conta:
        - Autorizo utilizar o limite de crédito, incluindo o Cheque Especial, se contratados, quando não houver saldo em conta: # Este campo é um checkbox. Preencher "Sim", caso o usuário marque esta opção e "Não", caso não identifique marcação da caixa de seleção.
        - Autorizo o débito do valor da(s) parcela(s) vencida(s), inclusive de valor(es) parcial(is) (Os encargos serão incorporados nas parcelas seguintes, conforme detalhado em contrato): # Este campo é um checkbox. Preencher "Sim", caso o usuário marque esta opção e "Não", caso não identifique marcação da caixa de seleção.
- Dados do(s) 1º Vendedor(es) Pessoa Física/Pessoa Jurídica:
    - Nome Completo / Razão Social:
    - CPF/CNPJ/MF:
    - Profissão:
    - E-mail:
    - Estado Civil:
    - Campo obrigatório para quem não é casado. Vive em união estável? # Este campo é identificado por um checkbox. Em <raw-text>, checkboxes preenchidas são identificadas com "[Y]", "Y]" ou variações dessa estrutura. Caso se depare com linhas que contenham "Sim" e "Não", mas que não venham acompanhadas do identificador de preenchimento, interprete que o usuário não respondeu a essa pergunta e preencha com "N/A".
    - Forma de Recebimento: # Este campo é identificado por um checkbox. Em <raw-text>, checkboxes preenchidas são identificadas com "[Y]", "Y]" ou variações dessa estrutura. Caso se depare com linhas que contenham "Sim" e "Não", mas que não venham acompanhadas do identificador de preenchimento, interprete que o usuário não respondeu a essa pergunta e preencha com "N/A".
    - Banco:
    - Agência:
    - Dígito:
    - Conta:
    - Dígito:
- Dados do(s) 2º Vendedor(es) Pessoa Física/Pessoa Jurídica:
    - Nome Completo / Razão Social:
    - CPF/CNPJ/MF:
    - Profissão:
    - E-mail:
    - Estado Civil:
    - Campo obrigatório para quem não é casado. Vive em união estável? # Este campo é identificado por um checkbox. Em <raw-text>, checkboxes preenchidas são identificadas com "[Y]", "Y]" ou variações dessa estrutura. Caso se depare com linhas que contenham "Sim" e "Não", mas que não venham acompanhadas do identificador de preenchimento, interprete que o usuário não respondeu a essa pergunta e preencha com "N/A".
    - Forma de Recebimento: # Este campo é identificado por um checkbox. Em <raw-text>, checkboxes preenchidas são identificadas com "[Y]", "Y]" ou variações dessa estrutura. Caso se depare com linhas que contenham "Sim" e "Não", mas que não venham acompanhadas do identificador de preenchimento, interprete que o usuário não respondeu a essa pergunta e preencha com "N/A".
    - Banco:
    - Agência:
    - Dígito:
    - Conta:
    - Dígito:
- Dados do Imóvel a ser Financiado
    - Endereço:
    - Número:
    - Complemento:
    - Quantidade de Vagas:
    - N° de Vagas:
    - Quantidade Depósito / Box:
    - N° Depósito / Box:
- Condições da Operação (todos os itens deste bloco são de preenchimento obrigatório):
    - Valor da Compra/Venda: # Valor monetário, em R$. Exemplo de preenchimento: R$ 1.000.000,00
    - Valor de Financiamento: # Valor monetário, em R$. Exemplo de preenchimento: R$ 1.000.000,00
    - Irá utilizar o FGTS: # Este campo é identificado por um checkbox. Em <raw-text>, checkboxes preenchidas são identificadas com "[Y]", "Y]" ou variações dessa estrutura. Caso se depare com linhas que contenham "Sim" e "Não", mas que não venham acompanhadas do identificador de preenchimento, interprete que o usuário não respondeu a essa pergunta e preencha com "N/A".
    - Prazo de Amortização: # Valor numérico, em meses. Exemplo de preenchimento: 360
    - Dia base para pagamento das prestações (De 01 a 28): # É um campo textual. Exemplo: 30 DIAS APÓS A ASSINATURA DO CONTRATO
    - Sistema de Amortização: # # Este campo é identificado por um checkbox. As opções de preenchimento são "SAC - Sistema de Amortização Constante" ou "Tabela PRICE".
    - Deseja incluir despesas cartorárias no financiamento: # Este campo é identificado por um checkbox. As opções de preenchimento são "Sim" ou "Não".
- Aceite Registro Eletrônico (Assinatura Digital): # Este campo é identificado por um checkbox. As opções de preenchimento são "Sim" ou "Não".
- Declarações do (s) Comprador (es):
    - O(s) Comprador(es) concordam com a dispensa? # Este campo é identificado por um checkbox. As opções de preenchimento são "Sim" ou "Não".
    - Declaração de inexistência de débitos condominais: # Este campo é identificado por um checkbox. As opções de preenchimento são "Sim" ou "Não".
    - Certidão Negativa de Impostos e Taxas Municipais: # Este campo é identificado por um checkbox. As opções de preenchimento são "Sim" ou "Não".
    - Declaração de regularidade de foro (para imóveis foreiros): # Este campo é identificado por um checkbox. As opções de preenchimento são "Sim" ou "Não".
'''

